name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up the environment and retrieve the terraform state
      - name: Prepare Terraform state
        run: |
          mkdir -p ./.terraform
          npx wrangler kv:key get --namespace-id=${{ env.tfstate_kv }} terraform.tfstate > ./.terraform/terraform.tfstate || echo '{"version": 4, "terraform_version": "1.5.0", "serial": 0, "lineage": "00000000-0000-0000-0000-000000000000", "outputs": {}, "resources": []}' > ./.terraform/terraform.tfstate

      # Deploy to Cloudflare using Wrangler
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
